### ISSUE TITLE
About Installation

### ISSUE THREAD

**Issue by Shuntw6096** [Dayan-Guan/UaDAN#2]
Hi, @Dayan-Guan , @khanh-moriaty 
thanks for your code, and there seems to be no setup.py.
```
conda env create -f environment.yaml
conda activate uadan
python setup.py build develop
pip install torchvision==0.2.1
```
Thanks.

**Comment by Shuntw6096** [comment]
Hi, Mapillary Vistas Dataset has two versions now, v1.2 and v2.0, which one is used in paper?
And how many images are in the training set for each domain in ```City2Vistas``` experiment?
Thanks.

**Comment by Dayan-Guan** [comment]
Hi @Shuntw6096,
The 'setup.py' has been uploaded. Please check.

**Comment by Dayan-Guan** [comment]
For Mapillary Vistas Dataset, please download the zipped volumes (v1.2 and v2.0) and then unzip all them into the same directory.

Please check the Experimental Setup in the Section IV of our paper for training details such as how many images are in the training set for each domain.

**Comment by Shuntw6096** [comment]
Hi, @Dayan-Guan, thanks for your reply, I found that some files are missing compared to [Domain-Adaptive-Faster-RCNN-PyTorch](https://github.com/krumo/Domain-Adaptive-Faster-RCNN-PyTorch) when I run evaluation for vistas ```python tools/test_net.py --config-file "configs/UaDAN_City2Vistas.yaml" MODEL.WEIGHT "pretrained_models/UaDAN_City2Vistas.pth"```
```
Traceback (most recent call last):
  File "tools/test_net.py", line 4, in <module>
    from maskrcnn_benchmark.utils.env import setup_environment  # noqa F401 isort:skip
ModuleNotFoundError: No module named 'maskrcnn_benchmark.utils.env'
```
Thanks.

**Comment by Dayan-Guan** [comment]
Fixed. Hi @Shuntw6096, thanks for your message.

**Comment by Shuntw6096** [comment]
Hi, @Dayan-Guan, thanks for your reply, `tools/test_net.py` still does not work, there seems that some files are missing.
https://github.com/Dayan-Guan/UaDAN/blob/4e2fb8e19940cfee74883ca0aa67efcce5162b5b/tools/test_net.py#L10
https://github.com/Dayan-Guan/UaDAN/blob/4e2fb8e19940cfee74883ca0aa67efcce5162b5b/tools/test_net.py#L13
Thanks.

**Comment by Dayan-Guan** [comment]
Hi @Shuntw6096 , I have found that

**Comment by Dayan-Guan** [comment]
Hi @Shuntw6096 , I have uploaded the missing files and succeed to test and train the codes after git clone the repo. Please check, thanks!

**Comment by Shuntw6096** [comment]
Hi, @Dayan-Guan , thanks for your code, I had ran the cityscapes -> vistas experiment, I test on my docker, cuda 9.0,  torch version is 1.1, torchvision version is 0.3.0.
``` dockerfile
FROM nvcr.io/nvidia/pytorch:18.04-py3
RUN pip install --upgrade pip
RUN pip uninstall torch torchvision torchtext -y
RUN pip install --no-cache-dir torch==1.1.0 -f https://download.pytorch.org/whl/cu90/torch_stable.html
RUN pip install --no-cache-dir torchvision==0.3.0
RUN pip install --no-cache-dir ipython ninja yacs cython matplotlib tqdm opencv-python pycocotools
ENV TZ=Asia/Taipei
RUN apt update
RUN apt install libgl1-mesa-glx libglib2.0-0 libsm6 libxrender1 libxext6 -y && apt install -y --no-install-recommends tzdata && rm -rf /var/lib/apt/lists/*
WORKDIR /home/
```
``` bash
# run docker
sudo docker run -it --rm --shm-size 16G --gpus all -v $REPO_PATH:/home/UaDAN -v $DATA_PATH:/home/Data $IMAGE_TAG_NAME /bin/bash
```
cityscapes -> vista performance (voc metric), it is better than the results in the paper
|   | person | rider | car | truck | bus | train | motorcycle | bicycle | mAP |
| :-----:|:-----:|:-----:|:------:| -----:|:-----:| -----:|:-----:|:-----:|:-------:|
| UaDAN | 38.1 | 34.6 | 56.7 | 23.3 | 26.2 | 30.3 | 32.2 | 33.7 | 34.4 |

Thanks.
